mongodb:
  host: malo.8gkpr.mongodb.net
  port: 27017
  database: malo
  user: shoes_store
  pass: admin

encryption:
  signning_method: HS256
  jwt_secret: malo_system
  jwt_exp: 2
  jwt_pol: 59a795909e65177c27fcdd87
  refresh_token_ttl: 1440 # 1440 hours = 60 days

rabbit_instance:
  amqp: amqps://zvxkuyav:pGg-S6eemfqgpA9mIA27rfJVRfYUe5Sz@armadillo.rmq.cloudamqp.com/zvxkuyav
  exchange: order-streaming
  routing_key: insert,update
  queue: order-queue
  tag: MALO
  timeout_retry: 3

aws:
  region: ap-southeast-2
  access_key_id: AKIA3JWXSCUR7Z2W6KHK
  secret_access_id: PMlQggqLz0w31GmA3Cu8cZCAeXegf88nPHiZh5LX